apiVersion: example.com/v1
kind: MysqlFamily
metadata:
  name: demo-mariadb
spec:
  # Optional, default is docker.io/mariadb:10, must suppport:
  #   mariadb:10.1, mariadb:10.0
  #   mysql:5
  #   mysql:5.7, mysql:5.6, mysql:5.5
  # May support:
  #   mariadb:5
  # Plan to support custome image, for example:
  # image:
  #   nameValues:
  #   - name: version
  #     value: mariadb10.2
  #   docker: 'docker.io/tangfeixiong/mariadb:latest'
  image: {}
  # Follow https://mariadb.com/kb/en/library/what-is-mariadb-galera-cluster/
  #   cluster: Galera, Replication
  # Follow https://dev.mysql.com/downloads/cluster/
  #   cluster: Ndb, Replication
  # No clustering
  #   cluster: None
  cluster: Galera
  mariadbTemplate:
    # Thus total members are replicationSlaves + masters
    replicationSlaves: 1
    # According redis documention, in high availability, hashSlots are not required
    #    if only one slaves, hash slots must be 16384
    #    in multiple slaves, when hash slots value is 0, means auto data sharding, for example:
    #        for 6 nodes with 3 masters and 3 slaves, the slots are sharding as 0-5500, 5501-11000, 11001-16383
    #    for non-zero value, it is firstly meet 1st slave, then 2nd slave, and 3rd...
    hashSlots: 0
  # According redis documention, in master-slave model, sentinels are not required
  mysqlTemplate:
    quorum: 2
