apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    component: redis
    redis: {{.ResourceName}} # my-redis
  name: {{.Name}} # my-redis
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: client
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: gossip
    port: 16379
    protocol: TCP
    targetPort: 16379
  selector:
    app: redis
    component: redis
    redis: {{.ResourceName}}
  #sessionAffinity: None
  #type: ClusterIP