apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
    heritage: repository
    name: registry
  name: registry
  # namespace: stackdocker
spec:
  clusterIP: None
  ports:
  - name: registry
    # nodePort: 30005  # Or Kubernetes allocate one automatically
    port: 5000
    protocol: TCP
  selector:
    name: registry
  # type: NodePort
