kind: PersistentVolume
apiVersion: v1
metadata:
  name: sample-local-volume-3
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data3"